server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov...IB
            clientSecret: 081...e27e
          google:
            clientId: 956...mr.apps.googleusercontent.com
            clientSecret: G...YM
          ohads:
            provider: ohads-provider
            clientId: ohadclientid
            clientSecret: ohadclientsecret
#            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/ohads
            scope: openid, email
            client-name: UAA

        provider:
          ohads-provider:
            issuer-uri: http://auth-server:9000
            #            authorization-uri: http://auth-server:9000/uaa/oauth/authorize
            #            token-uri: http://auth-server:9000/uaa/oauth/token
#            user-info-uri: http://auth-server:9000/uaa/userinfo
            user-name-attribute: sub
#            jwk-set-uri: http://auth-server:9000/uaa/token_keys


logging:
  level:
    org.springframework.security: TRACE
