server:
  port: 8090

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/issuer
#          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

logging:
  level:
    org.springframework.security: TRACE
